[toolchain]

[features]
seeds = false
skip-lint = false

#[programs.localnet]
[programs.devnet]
transfer_token_cpi = "8eMr4GobsfuPfJAq2eqpBz5uAZuHkx77RFSHiYJWWSpU"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "/Users/balance-guven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
